---
title: "Titanic Survivors"
author: "Faizan Ali"
date: "Friday, October 24, 2014"
output:
  html_document:
    fig_caption: yes
    number_sections: yes
---



```{r}
train <- read.csv("C:/Users/stifler/Downloads/study material/OCW/UN data Analysis/Python_utils/Kaggle/titanic/train.csv")
test <- read.csv("C:/Users/stifler/Downloads/study material/OCW/UN data Analysis/Python_utils/Kaggle/titanic/test.csv")
```

```{r}
prop.table(table(train$Survived))
```

```{r}
train$Child <- 0
train$Child[train$Age < 18] <- 1
aggregate(Survived ~ Child + Sex, data = train, FUN = function(x) {sum(x)/length(x)} )
```

```{r}
train$Fare2 <- '30+'
train$Fare2[train$Fare < 30 & train$Fare >= 20] <- '20-30'
train$Fare2[train$Fare < 20 & train$Fare >= 10] <- '10-20'
train$Fare2[train$Fare < 10] <- '<10'
aggregate(Survived ~ Fare2 + Pclass + Sex, data=train, FUN=function(x) {sum(x)/length(x)})
```

```{r,warning=FALSE}
library(rpart)
```

```{r}
test$Survived <- 0
test$Survived[test$Sex == 'female'] <- 1
test$Survived[test$Sex == 'female' & test$Pclass == '3'] <- 0
```

```{r}
fit <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, data=train, method="class")
```

```{r,warning=FALSE}
library(rattle)
library(rpart.plot)
library(RColorBrewer)
```

```{r}
fancyRpartPlot(fit)
```

```{r}
Prediction <- predict(fit,test,type = "class")
```
test$Survived <- NA
combi <- rbind(train,test)
head(combi,3)
```


